<a href="https://colab.research.google.com/github/reshmamk115/numpy/blob/main/data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np    #numerical python

#array  collection of data with same datatype(homogenous)
a=np.array([1,2,3.0,4])
print(a)

[1. 2. 3. 4.]


In [ ]:
#slicing
b=np.array([1,2,3,4,5])
b[0:2]
b[-1:-3:-1]
b[3:5]

array([4, 5])

In [ ]:
#dimension

a=np.array([0])
a.ndim       #dim=1 for a vector

1

In [ ]:
b=np.array([[1,2],[4,5]])
b.ndim        #dim=2 for matrix

b.shape

(2, 2)

In [ ]:
#create a 2*2 matrix 2,3,4,5


c=np.array([[2,3],[4,5]])
print(c)

print(c.shape)
print(c.ndim)

print(c.size)       #gives total number of elements

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
#create a 2*3 matrix amd print size,shape,dimension


p=np.array([[1,5,9],[6,4,2]])
print(p)
print(p.shape)
print(p.size)
print(p.ndim)

[[1 5 9]
 [6 4 2]]
(2, 3)
6
2


In [ ]:
#create a 4*2 matrix print its size shape dimension

i=np.array([[8,6],[2,6],[4,1],[5,2]])
print(i)
print(i.size)
print(i.shape)
print(i.ndim)

[[8 6]
 [2 6]
 [4 1]
 [5 2]]
8
(4, 2)
2


In [ ]:
#create a 4*4 matrix

s=np.array([[1,2,3,6],[7,8,9,4],[5,6,1,2],[5,2,3,9]])
print(s)
print(s.size)
print(s.shape)
print(s.ndim)

[[1 2 3 6]
 [7 8 9 4]
 [5 6 1 2]
 [5 2 3 9]]
16
(4, 4)
2


In [ ]:
import numpy as np
s=np.array([[1,2,3,6],[7,8,9,4],[5,6,1,2],[5,2,3,9]])
print(s)
s[0]       #gives 0th row
s[:,0]    #gives 0th column

[[1 2 3 6]
 [7 8 9 4]
 [5 6 1 2]
 [5 2 3 9]]


array([1, 7, 5, 5])

In [ ]:
s[1,1]       #elemnt based on index ---(row,column)

np.int64(8)

In [ ]:
s[3,2:]          #for more than one element

array([3, 9])

In [ ]:
s[2:,2:]

array([[1, 2],
       [3, 9]])

In [ ]:
s[2:,1:3]

array([[6, 1],
       [2, 3]])

In [ ]:
s[1:3,3]

array([4, 2])

In [ ]:
s[1:3,0:3]

array([[7, 8, 9],
       [5, 6, 1]])

In [ ]:
s[0:3,1:]

array([[2, 3, 6],
       [8, 9, 4],
       [6, 1, 2]])

In [ ]:
s[1:,0:]

array([[7, 8, 9, 4],
       [5, 6, 1, 2],
       [5, 2, 3, 9]])

In [ ]:
s[0:,1]

array([2, 8, 6, 2])

In [ ]:
#zero matrix

z=np.zeros([3,3],dtype=int)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
z=np.zeros([3,3,3],dtype=complex)
print(z)

[[[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]]


In [ ]:
z=np.zeros([2,3,3],dtype=int)
print(z)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
#one matrix

z=np.ones([3,3])
print(z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z=np.ones([3,3],dtype=int)
print(z)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#create two 2*2 matrix


a=np.array([[1,2],[3,4]])
print(a)
b=np.array([[1,8],[6,4]])
print(b)
a.shape
b.shape

[[1 2]
 [3 4]]
[[1 8]
 [6 4]]


(2, 2)

In [ ]:
#matrix addition

print(a+b)

[[ 2 10]
 [ 9  8]]


In [ ]:
#matrix subtraction

print(a-b)

#matrix multiplication

print(a@b)

print(a.dot(b))

[[ 0 -6]
 [-3  0]]
[[13 16]
 [27 40]]
[[13 16]
 [27 40]]


In [ ]:
#matrix division

print(a/b)

[[1.   0.25]
 [0.5  1.  ]]


In [ ]:
#full matrix


d=np.full([3,3],4,dtype=int)
print(d)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [ ]:
#create a 3*4 matrix with value 9 and dtype complex

g=np.full([3,4],9,dtype=complex)
print(g)

[[9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]]


In [ ]:
#identity matrix

i=np.identity(3,dtype=int)
print(i)

z=np.eye(2,dtype=int)
print(z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0]
 [0 1]]


In [ ]:
#create a 4*4 matrix

p=np.array([[1,4,7,8],[8,2,3,4],[5,1,9,2],[8,1,4,5]])
print(p)
print(p.size)

[[1 4 7 8]
 [8 2 3 4]
 [5 1 9 2]
 [8 1 4 5]]
16


In [ ]:
a=p.reshape(8,2)
print(a)

[[1 4]
 [7 8]
 [8 2]
 [3 4]
 [5 1]
 [9 2]
 [8 1]
 [4 5]]


In [ ]:
#arange

a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
#create 5*2 matrix using arange

s=np.arange(1,11).reshape(5,2)
print(s)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#create a 3*3 matrix with float values


a=np.array([[2.8,3.2,1.5],[5.4,4.6,9.2],[2.6,8.1,2.7]])
print(a)

[[2.8 3.2 1.5]
 [5.4 4.6 9.2]
 [2.6 8.1 2.7]]


In [ ]:
#floor

o=np.floor(a)
o

array([[2., 3., 1.],
       [5., 4., 9.],
       [2., 8., 2.]])

In [ ]:
#ceil


s=np.ceil(a)
s

array([[ 3.,  4.,  2.],
       [ 6.,  5., 10.],
       [ 3.,  9.,  3.]])

In [ ]:
#round

z=np.round(a)
z

array([[3., 3., 2.],
       [5., 5., 9.],
       [3., 8., 3.]])

In [9]:
#create 3*3 matrix
import numpy as np
a=np.arange(1,10).reshape(3,3)
print(a)
a.max()
a.max(axis=1)          #max of row
a.max(axis=0)          #max of column

a.max()
a.min()

a.sum()         #total sum
a.sum(axis=1)    #sum of row
np.sqrt(a)    #sqrt of each element
np.sin(a)
np.cos(a)
np.tan(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [10]:
#flatten    -  to convert to one-dimension

a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#sort

#create a 3*3 matrix
a=np.array([[1,4,5],[8,7,3],[9,12,4]])
print(a)
b=np.sort(a,axis=0)     #sorts based on column
print(b)
c=np.argsort(a,axis=1)     #sorts on basis of index
print(c)


[[ 1  4  5]
 [ 8  7  3]
 [ 9 12  4]]
[[ 1  4  3]
 [ 8  7  4]
 [ 9 12  5]]
[[0 1 2]
 [2 1 0]
 [2 0 1]]
